apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
- ingress.yaml
namespace: python-app-blue
images:
- name: hello-gitops
  newName: ai2humanize/hello-gitops
  newTag: a2cea1c60ff7a38b5abc1b7a44c037e4e6435dca
