apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
- ingress.yaml
namespace: python-app-blue
images:
- name: hello-gitops
  newName: ai2humanize/hello-gitops
  newTag: ae69d3d4fc83dd5613af3458efcd13e57bd18d02
